SELECT
    IF(s.MARKS > 70, NAME, 'NULL') AS THRESHHOLD,
    (SELECT 
        GRADE
     FROM 
        GRADES g
     WHERE (g.MIN_MARK <= s.MARKS) AND (s.MARKS <= g.MAX_MARK)) AS STUDENTGRADE,
     s.MARKS
FROM 
    STUDENTS s
ORDER BY
    STUDENTGRADE DESC, NAME, MARKS
