SELECT
    IF(s.MARKS > 70, NAME, 'NULL') AS THRESHHOLD,
    (SELECT 
        GRADE
     FROM 
        GRADES g
     WHERE (g.MIN_MARK <= s.MARKS) AND (s.MARKS <= g.MAX_MARK)) AS STUDENTGRADE,
     s.MARKS
FROM 
    STUDENTS s
ORDER BY
    STUDENTGRADE DESC, NAME, MARKS
    
-- ALTERNATIVE USING INNER JOIN (LEFT JOIN WORKS AS WELL)

SELECT
    IF(s.MARKS > 70, NAME, 'NULL'),
    g.GRADE,
    s.MARKS
FROM 
    STUDENTS s INNER JOIN GRADES g ON s.MARKS BETWEEN g.MIN_MARK AND g.MAX_MARK
ORDER BY
    g.GRADE DESC, NAME, MARKS
